
DEFAULT_TICKER = "AAPL"
HISTORICAL_YEARS = 3
WINDOW_SIZE = 60
TRAIN_SPLIT = 0.80
LSTM_UNITS = 64
EPOCHS = 25
BATCH_SIZE = 32
MODEL_DIR = "saved_models"
MODEL_MAX_AGE_DAYS = 7       # auto-retrain stale models
DEFAULT_FORECAST_DAYS = 7
MAX_FORECAST_DAYS = 30