import React from 'react';

const TARGET_DESCRIPTION = {
  price: 'Cumulative log return r(t,h) = ln(P(t+h) / P(t)); prices reconstructed from the latest close.',
  trend: 'One three-way call per forecast origin: sign of the CUMULATIVE h-day log return with a volatility-aware neutral band (Down/Neutral/Up softmax).',
  volatility: 'Future realised volatility over the selected horizon; the displayed range is a Gaussian model-implied scenario generated by a causal statistical baseline.',
  returnDistribution: 'Cumulative return location and variance from a certified Student-t distribution; prices are reconstructed from the latest close.',
};

function row(label, value) {
  return (
    <div className="model-card-row" key={label}>
      <span className="mc-label">{label}</span>
      <span className="mc-value">{value}</span>
    </div>
  );
}

function displayModelName(model) {
  const names = {
    garch_11: 'GARCH(1,1) MLE',
    rolling_mean: 'Rolling Mean (60d)',
    har_rv: 'HAR-RV',
    ewma: 'EWMA (0.94)',
    persistence: 'Persistence',
  };
  return names[model] || model || 'not reported';
}

/**
 * Lightweight methodology card. Facts only, derived from the prediction
 * payload; no marketing language. Renders nothing without a payload.
 */
export default function ModelCard({ data: stockData }) {
  const metadata = stockData?.metadata;
  if (!metadata) return null;
  const isTrend = stockData.direction != null;
  const isVolatility = metadata.engine?.certified_head === 'volatility' || stockData.volatility_cone != null;
  const isBaseline = metadata.engine?.baseline_fallback === true
    || metadata.engine?.execution_mode === 'baseline'
    || stockData.forecast_status?.state === 'baseline';
  const hasReturnDistribution = metadata.engine?.certified_head === 'return_distribution'
    && Array.isArray(stockData.predicted_prices);
  const engineRole = metadata.engine?.role || 'unknown';
  const snapshot = metadata.data_snapshot || {};
  const qualityStatus = snapshot.quality?.status;
  const dataProvider = metadata.data_provider || snapshot.provider;
  const dataAsOf = metadata.data_as_of || snapshot.as_of;
  const selectedModel = stockData.forecast?.model || metadata.selected_model;

  return (
    <details className="panel-card" id="modelCard">
      <summary className="panel-header">
        <h3>Model card &amp; methodology</h3>
      </summary>
      <div className="model-card-body">
        {row('Target', hasReturnDistribution
          ? TARGET_DESCRIPTION.returnDistribution
          : TARGET_DESCRIPTION[isVolatility ? 'volatility' : isTrend ? 'trend' : 'price'])}
        {row('Lookback window', `${metadata.window_size ?? '?'} sessions`)}
        {row('Forecast horizon', `${stockData.forecast_days ?? '?'} ${isVolatility ? 'session(s)' : 'day(s)'}`)}
        {row(
          'Model',
          isVolatility
            ? `${displayModelName(selectedModel)} (${engineRole})`
            : `${metadata.engine?.family ?? 'baseline'} (${engineRole})`
        )}
        {row(
          'Model state',
          metadata.engine?.execution_mode === 'server_artifact_loaded'
            ? 'Signed server artifact loaded'
            : isBaseline
              ? 'Causal statistical baseline'
            : metadata.engine?.role === 'baseline_fallback'
              ? 'Explicit baseline fallback'
              : metadata.engine?.cache_status || 'Signed server evaluation'
        )}
        {row('Feature count', String(metadata.feature_count ?? '?'))}
        {row('Schema version', `${metadata.schema_version ?? '?'}`)}
        {row('Scaling', isVolatility ? (isBaseline ? 'Causal transforms; no fitted scaler' : 'Frozen train-only scaler from the signed release') : 'Robust median/IQR, fit on the training partition only')}
        {row(
          'Evaluation split',
          isVolatility
            ? (isBaseline
              ? 'Baseline definition; no learned-model evaluation is claimed'
              : metadata.metric_source === 'sealed_holdout_once'
              ? 'One physically sealed holdout opened once after frozen routing'
              : 'Locked purged walk-forward plus temporal and ticker-transfer holdouts')
            : '80/20 chronological with a horizon-purged boundary; metrics are out-of-sample'
        )}
        {row('Metric source', metadata.metric_source || 'not reported')}
        {row('Data provider', dataProvider || 'not reported')}
        {row('Market data through', dataAsOf || 'not reported')}
        {row('Code commit', metadata.code_commit || 'not reported')}
        {row(
          'Forecast fingerprint',
          metadata.forecast_fingerprint
            ? `${String(metadata.forecast_fingerprint).slice(0, 16)}…`
            : 'not reported'
        )}
        {row(
          'Location caveat',
          hasReturnDistribution
            ? 'Terminal Student-t return location and variance are certified; intermediate chart points linearly interpolate cumulative moments, and direction is not certified.'
            : isVolatility
              ? (isBaseline ? 'This is a transparent causal baseline. The range is a Gaussian model-implied scenario, not a point price forecast or calibrated confidence interval.' : 'The center line is an explicit matched persistence baseline; only the volatility scenario range is learned and certified.')
              : 'Displayed future forecast comes from a model refitted on all history; it is not independently validated.'
        )}
        {row(
          'Data adjustment',
          snapshot.adjusted_prices ? 'Split/dividend-adjusted closes (auto_adjust)' : 'Adjustment policy not reported'
        )}
        {row(
          'Data quality',
          qualityStatus === 'clean'
            ? 'Clean'
            : qualityStatus === 'annotated'
              ? 'Annotated warnings — see snapshot metadata'
              : 'Not reported'
        )}
        {row('Snapshot', metadata.snapshot_id ? `${String(metadata.snapshot_id).slice(0, 12)}…` : 'n/a')}
        <p className="mc-limitations">
          Limitations: daily OHLCV carries limited predictive signal; simple
          baselines are often competitive; nothing here is financial advice.
        </p>
      </div>
    </details>
  );
}
