"""Leakage-safe volatility forecasting research package.

Provides canonical empirical benchmarking pipelines, causal feature extractors,
GARCH(1,1) MLE parameter estimation, PyTorch softplus volatility models,
and paired asset-level bootstrap hypothesis testing.
"""

from .simple_pipeline import (
    NEWS_FEATURE_NAMES,
    PIPELINE_VERSION,
    TARGET_VERSION,
    ChronologicalSplit,
    LSTMConfig,
    NonTradingSessionError,
    VolatilityConfig,
    VolatilityExamples,
    assert_label_purged,
    baseline_predictions,
    build_causal_news_features,
    build_examples,
    build_feature_frame,
    causal_log_har_forecasts,
    chronological_split,
    evaluate_benchmark,
    evaluate_conformal_volatility_intervals,
    evaluate_price_diffusion_cone,
    experiment_metadata,
    fit_garch11_baseline,
    fit_garch11_mle_from_returns,
    fit_har_baseline,
    get_session_close_utc,
    learned_predictions,
    lstm_predictions,
    qlike_loss,
    realised_volatility,
    select_validation_model,
    validate_ohlcv,
    volatility_metrics,
)

__all__ = [
    "NEWS_FEATURE_NAMES",
    "PIPELINE_VERSION",
    "TARGET_VERSION",
    "ChronologicalSplit",
    "LSTMConfig",
    "NonTradingSessionError",
    "VolatilityConfig",
    "VolatilityExamples",
    "assert_label_purged",
    "baseline_predictions",
    "build_causal_news_features",
    "build_examples",
    "build_feature_frame",
    "causal_log_har_forecasts",
    "chronological_split",
    "evaluate_benchmark",
    "evaluate_conformal_volatility_intervals",
    "evaluate_price_diffusion_cone",
    "experiment_metadata",
    "fit_garch11_baseline",
    "fit_garch11_mle_from_returns",
    "fit_har_baseline",
    "get_session_close_utc",
    "learned_predictions",
    "lstm_predictions",
    "qlike_loss",
    "realised_volatility",
    "select_validation_model",
    "validate_ohlcv",
    "volatility_metrics",
]
