"""External Ed25519 signature verification and key security contracts for V10.

CRITICAL SECURITY INVARIANTS:
- Private signing keys MUST NEVER be generated, created, or stored inside the repository tree.
- Private signing keys MUST NEVER be generated by training or research runner code.
- Only detached signature verification against external public keys is performed here.
"""

from __future__ import annotations

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
from cryptography.hazmat.primitives.serialization import load_pem_public_key


class ReleaseSignatureError(ValueError):
    """Raised when release bundle signature verification fails."""


def verify_detached_signature(
    data_bytes: bytes,
    signature_bytes: bytes,
    public_key_pem: bytes,
) -> bool:
    """Verify Ed25519 detached signature."""
    try:
        public_key = load_pem_public_key(public_key_pem)
        if not isinstance(public_key, Ed25519PublicKey):
            raise ReleaseSignatureError("Only Ed25519 public keys are supported.")
        public_key.verify(signature_bytes, data_bytes)
        return True
    except Exception as exc:
        raise ReleaseSignatureError(f"Signature verification failed: {exc}") from exc
