"""External Ed25519 signature verification and detached signing contracts for V10.

CRITICAL SECURITY INVARIANTS:
- Private signing keys MUST NEVER be generated, created, or stored inside the repository tree.
- Private signing keys MUST NEVER be generated by training or research runner code.
- Detached external signing signs verified release manifest bytes.
- Signature verification strictly fails closed if public key is missing or signature is invalid.
"""

from __future__ import annotations

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey, Ed25519PublicKey
from cryptography.hazmat.primitives.serialization import load_pem_public_key


class ReleaseSignatureError(ValueError):
    """Raised when release bundle signature verification fails."""


def sign_release_manifest_detached(
    manifest_bytes: bytes,
    private_key: Ed25519PrivateKey,
) -> bytes:
    """External offline signing function (used exclusively outside training tree)."""
    return private_key.sign(manifest_bytes)


def verify_detached_signature(
    data_bytes: bytes,
    signature_bytes: bytes,
    public_key_pem: bytes,
) -> bool:
    """Verify Ed25519 detached signature strictly failing closed."""
    if not public_key_pem or not signature_bytes:
        raise ReleaseSignatureError("Public key and signature bytes are strictly required.")
    try:
        public_key = load_pem_public_key(public_key_pem)
        if not isinstance(public_key, Ed25519PublicKey):
            raise ReleaseSignatureError("Only Ed25519 public keys are supported.")
        public_key.verify(signature_bytes, data_bytes)
        return True
    except Exception as exc:
        raise ReleaseSignatureError(f"Signature verification failed: {exc}") from exc
